# Generated by Django 4.1.3 on 2022-12-02 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(default='candidate', max_length=10)),
                ('otp_code', models.CharField(default='none', max_length=10)),
                ('ec_status', models.BooleanField(default=True)),
                ('status', models.BooleanField(default=True)),
                ('wallet_address', models.CharField(default='null', max_length=100)),
                ('wallet_key', models.CharField(default='null', max_length=100)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
